# Generated by Django 3.2.9 on 2021-11-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_neighbor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubNeighbor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SubNeighborname', models.CharField(max_length=200)),
                ('Neigbour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subdistrict')),
            ],
        ),
    ]
