# Generated by Django 3.2.9 on 2021-11-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_subneighbor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subneighbor',
            name='Neigbour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.neighbor'),
        ),
    ]
