# Generated by Django 3.2.8 on 2021-11-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_subneighbor_neigbour'),
    ]

    operations = [
        migrations.CreateModel(
            name='identification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IDType', models.CharField(max_length=200)),
                ('OtherID', models.IntegerField(blank=True)),
                ('IDNumber', models.IntegerField(blank=True)),
                ('IDissueBy', models.CharField(max_length=200)),
                ('IDdate', models.DateField(blank=True)),
                ('SecondID', models.FileField(null=True, upload_to='file/')),
            ],
        ),
    ]
