# Generated by Django 3.2.8 on 2021-11-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_identification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identification',
            old_name='SecondID',
            new_name='ScanedID',
        ),
    ]
