# Generated by Django 3.2.8 on 2021-11-10 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_identification_scanedid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='IDNumber',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='OtherID',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='PropertyMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PropertyNumber', models.PositiveIntegerField(blank=True)),
                ('Parcelmap', models.FileField(null=True, upload_to='parcelmap/')),
                ('MasterplanMap', models.FileField(null=True, upload_to='masterplanmap/')),
                ('RegistrationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.identification')),
            ],
        ),
        migrations.CreateModel(
            name='PlotNo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PlotNo', models.PositiveIntegerField(blank=True)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.district')),
                ('Neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.neighbor')),
                ('Propertymap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.propertymap')),
                ('SubDistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subdistrict')),
                ('SubNeighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.subneighbor')),
                ('identification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.identification')),
            ],
        ),
        migrations.CreateModel(
            name='Plotmap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Lenght', models.CharField(max_length=500)),
                ('Width', models.CharField(max_length=500)),
                ('RegistrationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.identification')),
            ],
        ),
    ]
