# Generated by Django 3.2.8 on 2021-11-12 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_purchaseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Landtype', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Notary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Notrayname', models.CharField(max_length=500)),
                ('YearEstablished', models.CharField(max_length=500)),
                ('Ownername', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Existingbuilding', models.CharField(max_length=500)),
                ('Landpurchaseamount', models.CharField(max_length=500)),
                ('PurchaseDate', models.DateField()),
                ('FileNO', models.PositiveIntegerField(blank=True)),
                ('LandUsetype', models.CharField(max_length=500)),
                ('Landwidth', models.CharField(max_length=500)),
                ('landlenght', models.CharField(max_length=500)),
                ('Landtype', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.landtype')),
                ('Notary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.notary')),
                ('Purchaseinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.purchaseinfo')),
            ],
        ),
    ]
