# Generated by Django 3.2.8 on 2021-11-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_landtype_notary_parcel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='id',
            new_name='Registrationid',
        ),
    ]
