# Generated by Django 3.2.8 on 2021-11-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rename_id_parcel_registrationid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellerinfo',
            fields=[
                ('Registrationid', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=500)),
                ('SecondName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('SurName', models.CharField(max_length=500)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('MobileNO1', models.CharField(max_length=500)),
                ('MobileNo2', models.CharField(max_length=500)),
                ('Email', models.CharField(max_length=500)),
                ('Parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.parcel')),
            ],
        ),
    ]
