# Generated by Django 3.2.8 on 2021-11-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_dhaxalayaal_dhaxalsubdoc_supportingdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhaxalayaal',
            name='Parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.parcel'),
        ),
        migrations.AlterField(
            model_name='dhaxalsubdoc',
            name='Parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.parcel'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='Landtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.landtype'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='Notary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.notary'),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='Parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.parcel'),
        ),
        migrations.AlterField(
            model_name='supportingdoc',
            name='Parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.parcel'),
        ),
    ]
