# Generated by Django 3.2.8 on 2021-11-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_bussinessregistration_bussinessregistrator_bussinessstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('RegistrationNo', models.AutoField(primary_key=True, serialize=False)),
                ('SequesnceNo', models.PositiveIntegerField(blank=True)),
                ('Longitude', models.CharField(max_length=500)),
                ('Latitude', models.CharField(max_length=500)),
                ('Attribute', models.CharField(max_length=500)),
                ('Parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.parcel')),
            ],
        ),
    ]
