# Generated by Django 3.2.8 on 2021-11-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='KalawarejinSubDoc',
            fields=[
                ('RegistrationID', models.AutoField(primary_key=True, serialize=False)),
                ('DhaxalDOC1', models.FileField(null=True, upload_to='DhaxalDOC1/')),
                ('DhaxalDOC2', models.FileField(null=True, upload_to='DhaxalDOC2/')),
                ('DhaxalDOC3', models.FileField(null=True, upload_to='DhaxalDOC3/')),
                ('DhaxalDOC4', models.FileField(null=True, upload_to='DhaxalDOC4/')),
                ('Parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.parcel')),
            ],
        ),
    ]
