# Generated by Django 3.2.8 on 2021-11-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_kalawarejinsubdoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRevenu',
            fields=[
                ('RegistrationNo', models.AutoField(primary_key=True, serialize=False)),
                ('TransNo', models.PositiveIntegerField(blank=True)),
                ('TaransDate', models.DateField()),
                ('Chargecode', models.CharField(max_length=500)),
                ('Transcurr', models.CharField(max_length=500)),
                ('GrNo', models.CharField(max_length=500)),
                ('Revenuetype', models.CharField(max_length=500)),
            ],
        ),
    ]
