# Generated by Django 3.2.8 on 2021-11-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_propertyrevenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrevenu',
            name='Parcel',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='mainapp.parcel'),
        ),
    ]
